#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycontainer
  template:
    metadata:
      labels:
        app: mycontainer
    spec:
      containers:
      - name: mycontainer
        image: #@ "{}/{}:{}".format(data.values.image.registry, data.values.image.name, data.values.image.tag)
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mycontainer-config
